name: Release-plz

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch: # This enables manual triggering from the UI
    inputs:
      # Optional inputs can be defined here
      force_update:
        description: 'Set to true to force update the release PR'
        required: false
        default: 'false'

jobs:
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'tarka' }}
    permissions:
      contents: write
      id-token: write
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
        with:
          command: release

  # release-plz-pr:
  #   name: Release-plz PR
  #   runs-on: ubuntu-latest
  #   if: ${{ github.repository_owner == 'tarka' }}
  #   permissions:
  #     pull-requests: write
  #     contents: write
  #   concurrency:
  #     group: release-plz-${{ github.ref }}
  #     cancel-in-progress: false
  #   steps:
  #     - *checkout
  #     - *install-rust
  #     - name: Run release-plz
  #       uses: release-plz/action@v0.5
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
  #       with:
  #         command: release-pr
