name: "Release Binaries"

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  upload-assets:
    name: ${{ matrix.shortname }}
    if: github.repository_owner == 'tarka'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            shortarch: linux-amd64
            os: ubuntu-22.04

          - target: aarch64-unknown-linux-gnu
            shortarch: linux-arm64
            os: ubuntu-22.04-arm

          - target: aarch64-apple-darwin
            shortarch: macos-amd64
            os: macos-14

          # - target: x86_64-unknown-freebsd
          #   os: ubuntu-22.04

    timeout-minutes: 60
    steps:

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Create additional release structure
        run: |
          mkdir -p etc/systemd/system etc/vicarian
          cp systemd/vicarian.service etc/systemd/system/
          cp examples/vicarian-tls-files.corn etc/vicarian/vicarian.corn
          touch etc/vicarian/secrets
          chmod o-rwx etc/vicarian/secrets

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: vicarian
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

          tar: all
          archive: $bin-$tag-${{ matrix.shortarch }}
          leading-dir: true
          bin-leading-dir: bin
          include: LICENSE,README.md,etc
